extends RefCounted
class_name BattleCoreServiceSpecs

const SCRIPT_BY_SLOT := {
    "id_factory": preload("res://src/shared/id_factory.gd"),
    "rng_service": preload("res://src/shared/rng_service.gd"),
    "legal_action_service": preload("res://src/battle_core/commands/legal_action_service.gd"),
    "domain_legality_service": preload("res://src/battle_core/commands/domain_legality_service.gd"),
    "command_builder": preload("res://src/battle_core/commands/command_builder.gd"),
    "command_validator": preload("res://src/battle_core/commands/command_validator.gd"),
    "battle_initializer": preload("res://src/battle_core/turn/battle_initializer.gd"),
    "action_queue_builder": preload("res://src/battle_core/turn/action_queue_builder.gd"),
    "turn_loop_controller": preload("res://src/battle_core/turn/turn_loop_controller.gd"),
    "turn_resolution_service": preload("res://src/battle_core/turn/turn_resolution_service.gd"),
    "turn_selection_resolver": preload("res://src/battle_core/turn/turn_selection_resolver.gd"),
    "turn_field_lifecycle_service": preload("res://src/battle_core/turn/turn_field_lifecycle_service.gd"),
    "turn_limit_scoring_service": preload("res://src/battle_core/turn/turn_limit_scoring_service.gd"),
    "battle_result_service": preload("res://src/battle_core/turn/battle_result_service.gd"),
    "runtime_guard_service": preload("res://src/battle_core/turn/runtime_guard_service.gd"),
    "action_executor": preload("res://src/battle_core/actions/action_executor.gd"),
    "action_chain_context_builder": preload("res://src/battle_core/actions/action_chain_context_builder.gd"),
    "action_start_phase_service": preload("res://src/battle_core/actions/action_start_phase_service.gd"),
    "action_skill_effect_service": preload("res://src/battle_core/actions/action_skill_effect_service.gd"),
    "action_execution_resolution_service": preload("res://src/battle_core/actions/action_execution_resolution_service.gd"),
    "action_domain_guard": preload("res://src/battle_core/actions/action_domain_guard.gd"),
    "action_cast_service": preload("res://src/battle_core/actions/action_cast_service.gd"),
    "action_cast_direct_damage_pipeline": preload("res://src/battle_core/actions/action_cast_direct_damage_pipeline.gd"),
    "action_cast_skill_effect_dispatch_pipeline": preload("res://src/battle_core/actions/action_cast_skill_effect_dispatch_pipeline.gd"),
    "action_hit_resolution_service": preload("res://src/battle_core/actions/action_hit_resolution_service.gd"),
    "power_bonus_resolver": preload("res://src/battle_core/actions/power_bonus_resolver.gd"),
    "switch_action_service": preload("res://src/battle_core/actions/switch_action_service.gd"),
    "action_log_service": preload("res://src/battle_core/actions/action_log_service.gd"),
    "target_resolver": preload("res://src/battle_core/actions/target_resolver.gd"),
    "stat_calculator": preload("res://src/battle_core/math/stat_calculator.gd"),
    "mp_service": preload("res://src/battle_core/math/mp_service.gd"),
    "hit_service": preload("res://src/battle_core/math/hit_service.gd"),
    "damage_service": preload("res://src/battle_core/math/damage_service.gd"),
    "combat_type_service": preload("res://src/battle_core/math/combat_type_service.gd"),
    "leave_service": preload("res://src/battle_core/lifecycle/leave_service.gd"),
    "lifecycle_retention_policy": preload("res://src/battle_core/lifecycle/lifecycle_retention_policy.gd"),
    "faint_resolver": preload("res://src/battle_core/lifecycle/faint_resolver.gd"),
    "faint_killer_attribution_service": preload("res://src/battle_core/lifecycle/faint_killer_attribution_service.gd"),
    "faint_leave_replacement_service": preload("res://src/battle_core/lifecycle/faint_leave_replacement_service.gd"),
    "replacement_selector": preload("res://src/battle_core/lifecycle/default_replacement_selector.gd"),
    "replacement_service": preload("res://src/battle_core/lifecycle/replacement_service.gd"),
    "trigger_dispatcher": preload("res://src/battle_core/effects/trigger_dispatcher.gd"),
    "trigger_batch_runner": preload("res://src/battle_core/effects/trigger_batch_runner.gd"),
    "effect_queue_service": preload("res://src/battle_core/effects/effect_queue_service.gd"),
    "payload_executor": preload("res://src/battle_core/effects/payload_executor.gd"),
    "payload_unit_target_helper": preload("res://src/battle_core/effects/payload_handlers/payload_unit_target_helper.gd"),
    "payload_effect_event_helper": preload("res://src/battle_core/effects/payload_handlers/payload_effect_event_helper.gd"),
    "payload_numeric_handler": preload("res://src/battle_core/effects/payload_handlers/payload_numeric_handler.gd"),
    "payload_damage_runtime_service": preload("res://src/battle_core/effects/payload_handlers/payload_damage_runtime_service.gd"),
    "payload_resource_runtime_service": preload("res://src/battle_core/effects/payload_handlers/payload_resource_runtime_service.gd"),
    "payload_stat_mod_runtime_service": preload("res://src/battle_core/effects/payload_handlers/payload_stat_mod_runtime_service.gd"),
    "payload_state_handler": preload("res://src/battle_core/effects/payload_handlers/payload_state_handler.gd"),
    "payload_forced_replace_handler": preload("res://src/battle_core/effects/payload_handlers/payload_forced_replace_handler.gd"),
    "effect_instance_service": preload("res://src/battle_core/effects/effect_instance_service.gd"),
    "effect_instance_dispatcher": preload("res://src/battle_core/effects/effect_instance_dispatcher.gd"),
    "rule_mod_service": preload("res://src/battle_core/effects/rule_mod_service.gd"),
    "rule_mod_value_resolver": preload("res://src/battle_core/effects/rule_mod_value_resolver.gd"),
    "passive_skill_service": preload("res://src/battle_core/passives/passive_skill_service.gd"),
    "passive_item_service": preload("res://src/battle_core/passives/passive_item_service.gd"),
    "field_service": preload("res://src/battle_core/passives/field_service.gd"),
    "field_apply_service": preload("res://src/battle_core/passives/field_apply_service.gd"),
    "domain_clash_orchestrator": preload("res://src/battle_core/passives/domain_clash_orchestrator.gd"),
    "field_apply_context_resolver": preload("res://src/battle_core/passives/field_apply_context_resolver.gd"),
    "field_apply_conflict_service": preload("res://src/battle_core/passives/field_apply_conflict_service.gd"),
    "field_apply_log_service": preload("res://src/battle_core/passives/field_apply_log_service.gd"),
    "field_apply_effect_runner": preload("res://src/battle_core/passives/field_apply_effect_runner.gd"),
    "battle_logger": preload("res://src/battle_core/logging/battle_logger.gd"),
    "log_event_builder": preload("res://src/battle_core/logging/log_event_builder.gd"),
    "public_snapshot_builder": preload("res://src/battle_core/facades/public_snapshot_builder.gd"),
    "replay_runner": preload("res://src/battle_core/logging/replay_runner.gd"),
}

const SERVICE_SPECS := [
    {"slot": "id_factory", "script": SCRIPT_BY_SLOT["id_factory"]},
    {"slot": "rng_service", "script": SCRIPT_BY_SLOT["rng_service"]},
    {"slot": "legal_action_service", "script": SCRIPT_BY_SLOT["legal_action_service"]},
    {"slot": "domain_legality_service", "script": SCRIPT_BY_SLOT["domain_legality_service"]},
    {"slot": "command_builder", "script": SCRIPT_BY_SLOT["command_builder"]},
    {"slot": "command_validator", "script": SCRIPT_BY_SLOT["command_validator"]},
    {"slot": "battle_initializer", "script": SCRIPT_BY_SLOT["battle_initializer"]},
    {"slot": "action_queue_builder", "script": SCRIPT_BY_SLOT["action_queue_builder"]},
    {"slot": "turn_loop_controller", "script": SCRIPT_BY_SLOT["turn_loop_controller"]},
    {"slot": "turn_resolution_service", "script": SCRIPT_BY_SLOT["turn_resolution_service"]},
    {"slot": "turn_selection_resolver", "script": SCRIPT_BY_SLOT["turn_selection_resolver"]},
    {"slot": "turn_field_lifecycle_service", "script": SCRIPT_BY_SLOT["turn_field_lifecycle_service"]},
    {"slot": "turn_limit_scoring_service", "script": SCRIPT_BY_SLOT["turn_limit_scoring_service"]},
    {"slot": "battle_result_service", "script": SCRIPT_BY_SLOT["battle_result_service"]},
    {"slot": "runtime_guard_service", "script": SCRIPT_BY_SLOT["runtime_guard_service"]},
    {"slot": "action_executor", "script": SCRIPT_BY_SLOT["action_executor"]},
    {"slot": "action_chain_context_builder", "script": SCRIPT_BY_SLOT["action_chain_context_builder"]},
    {"slot": "action_start_phase_service", "script": SCRIPT_BY_SLOT["action_start_phase_service"]},
    {"slot": "action_skill_effect_service", "script": SCRIPT_BY_SLOT["action_skill_effect_service"]},
    {"slot": "action_execution_resolution_service", "script": SCRIPT_BY_SLOT["action_execution_resolution_service"]},
    {"slot": "action_domain_guard", "script": SCRIPT_BY_SLOT["action_domain_guard"]},
    {"slot": "action_cast_service", "script": SCRIPT_BY_SLOT["action_cast_service"]},
    {"slot": "action_cast_direct_damage_pipeline", "script": SCRIPT_BY_SLOT["action_cast_direct_damage_pipeline"]},
    {"slot": "action_cast_skill_effect_dispatch_pipeline", "script": SCRIPT_BY_SLOT["action_cast_skill_effect_dispatch_pipeline"]},
    {"slot": "action_hit_resolution_service", "script": SCRIPT_BY_SLOT["action_hit_resolution_service"]},
    {"slot": "power_bonus_resolver", "script": SCRIPT_BY_SLOT["power_bonus_resolver"]},
    {"slot": "switch_action_service", "script": SCRIPT_BY_SLOT["switch_action_service"]},
    {"slot": "action_log_service", "script": SCRIPT_BY_SLOT["action_log_service"]},
    {"slot": "target_resolver", "script": SCRIPT_BY_SLOT["target_resolver"]},
    {"slot": "stat_calculator", "script": SCRIPT_BY_SLOT["stat_calculator"]},
    {"slot": "mp_service", "script": SCRIPT_BY_SLOT["mp_service"]},
    {"slot": "hit_service", "script": SCRIPT_BY_SLOT["hit_service"]},
    {"slot": "damage_service", "script": SCRIPT_BY_SLOT["damage_service"]},
    {"slot": "combat_type_service", "script": SCRIPT_BY_SLOT["combat_type_service"]},
    {"slot": "leave_service", "script": SCRIPT_BY_SLOT["leave_service"]},
    {"slot": "lifecycle_retention_policy", "script": SCRIPT_BY_SLOT["lifecycle_retention_policy"]},
    {"slot": "faint_resolver", "script": SCRIPT_BY_SLOT["faint_resolver"]},
    {"slot": "faint_killer_attribution_service", "script": SCRIPT_BY_SLOT["faint_killer_attribution_service"]},
    {"slot": "faint_leave_replacement_service", "script": SCRIPT_BY_SLOT["faint_leave_replacement_service"]},
    {"slot": "replacement_selector", "script": SCRIPT_BY_SLOT["replacement_selector"]},
    {"slot": "replacement_service", "script": SCRIPT_BY_SLOT["replacement_service"]},
    {"slot": "trigger_dispatcher", "script": SCRIPT_BY_SLOT["trigger_dispatcher"]},
    {"slot": "trigger_batch_runner", "script": SCRIPT_BY_SLOT["trigger_batch_runner"]},
    {"slot": "effect_queue_service", "script": SCRIPT_BY_SLOT["effect_queue_service"]},
    {"slot": "payload_executor", "script": SCRIPT_BY_SLOT["payload_executor"]},
    {"slot": "payload_unit_target_helper", "script": SCRIPT_BY_SLOT["payload_unit_target_helper"]},
    {"slot": "payload_effect_event_helper", "script": SCRIPT_BY_SLOT["payload_effect_event_helper"]},
    {"slot": "payload_numeric_handler", "script": SCRIPT_BY_SLOT["payload_numeric_handler"]},
    {"slot": "payload_damage_runtime_service", "script": SCRIPT_BY_SLOT["payload_damage_runtime_service"]},
    {"slot": "payload_resource_runtime_service", "script": SCRIPT_BY_SLOT["payload_resource_runtime_service"]},
    {"slot": "payload_stat_mod_runtime_service", "script": SCRIPT_BY_SLOT["payload_stat_mod_runtime_service"]},
    {"slot": "payload_state_handler", "script": SCRIPT_BY_SLOT["payload_state_handler"]},
    {"slot": "payload_forced_replace_handler", "script": SCRIPT_BY_SLOT["payload_forced_replace_handler"]},
    {"slot": "effect_instance_service", "script": SCRIPT_BY_SLOT["effect_instance_service"]},
    {"slot": "effect_instance_dispatcher", "script": SCRIPT_BY_SLOT["effect_instance_dispatcher"]},
    {"slot": "rule_mod_service", "script": SCRIPT_BY_SLOT["rule_mod_service"]},
    {"slot": "rule_mod_value_resolver", "script": SCRIPT_BY_SLOT["rule_mod_value_resolver"]},
    {"slot": "passive_skill_service", "script": SCRIPT_BY_SLOT["passive_skill_service"]},
    {"slot": "passive_item_service", "script": SCRIPT_BY_SLOT["passive_item_service"]},
    {"slot": "field_service", "script": SCRIPT_BY_SLOT["field_service"]},
    {"slot": "field_apply_service", "script": SCRIPT_BY_SLOT["field_apply_service"]},
    {"slot": "domain_clash_orchestrator", "script": SCRIPT_BY_SLOT["domain_clash_orchestrator"]},
    {"slot": "field_apply_context_resolver", "script": SCRIPT_BY_SLOT["field_apply_context_resolver"]},
    {"slot": "field_apply_conflict_service", "script": SCRIPT_BY_SLOT["field_apply_conflict_service"]},
    {"slot": "field_apply_log_service", "script": SCRIPT_BY_SLOT["field_apply_log_service"]},
    {"slot": "field_apply_effect_runner", "script": SCRIPT_BY_SLOT["field_apply_effect_runner"]},
    {"slot": "battle_logger", "script": SCRIPT_BY_SLOT["battle_logger"]},
    {"slot": "log_event_builder", "script": SCRIPT_BY_SLOT["log_event_builder"]},
    {"slot": "public_snapshot_builder", "script": SCRIPT_BY_SLOT["public_snapshot_builder"]},
    {"slot": "replay_runner", "script": SCRIPT_BY_SLOT["replay_runner"]},
]
