extends RefCounted
class_name BattleCoreServiceSpecs

const SERVICE_SLOTS := [
    "id_factory",
    "rng_service",
    "legal_action_service",
    "domain_legality_service",
    "command_builder",
    "command_validator",
    "battle_initializer",
    "action_queue_builder",
    "turn_loop_controller",
    "turn_resolution_service",
    "turn_selection_resolver",
    "turn_field_lifecycle_service",
    "turn_limit_scoring_service",
    "battle_result_service",
    "runtime_guard_service",
    "action_executor",
    "action_chain_context_builder",
    "action_start_phase_service",
    "action_skill_effect_service",
    "action_execution_resolution_service",
    "action_domain_guard",
    "action_cast_service",
    "action_cast_direct_damage_pipeline",
    "action_cast_skill_effect_dispatch_pipeline",
    "action_hit_resolution_service",
    "power_bonus_resolver",
    "switch_action_service",
    "action_log_service",
    "target_resolver",
    "stat_calculator",
    "mp_service",
    "hit_service",
    "damage_service",
    "combat_type_service",
    "leave_service",
    "lifecycle_retention_policy",
    "faint_resolver",
    "faint_killer_attribution_service",
    "faint_leave_replacement_service",
    "replacement_selector",
    "replacement_service",
    "trigger_dispatcher",
    "trigger_batch_runner",
    "effect_queue_service",
    "payload_executor",
    "payload_unit_target_helper",
    "payload_effect_event_helper",
    "payload_numeric_handler",
    "payload_damage_runtime_service",
    "payload_resource_runtime_service",
    "payload_stat_mod_runtime_service",
    "payload_state_handler",
    "payload_forced_replace_handler",
    "effect_instance_service",
    "effect_instance_dispatcher",
    "rule_mod_service",
    "rule_mod_value_resolver",
    "passive_skill_service",
    "passive_item_service",
    "field_service",
    "field_apply_service",
    "domain_clash_orchestrator",
    "field_apply_context_resolver",
    "field_apply_conflict_service",
    "field_apply_log_service",
    "field_apply_effect_runner",
    "battle_logger",
    "log_event_builder",
    "public_snapshot_builder",
    "replay_runner",
]

const SCRIPT_BY_SLOT := {
    "id_factory": preload("res://src/shared/id_factory.gd"),
    "rng_service": preload("res://src/shared/rng_service.gd"),
    "legal_action_service": preload("res://src/battle_core/commands/legal_action_service.gd"),
    "domain_legality_service": preload("res://src/battle_core/commands/domain_legality_service.gd"),
    "command_builder": preload("res://src/battle_core/commands/command_builder.gd"),
    "command_validator": preload("res://src/battle_core/commands/command_validator.gd"),
    "battle_initializer": preload("res://src/battle_core/turn/battle_initializer.gd"),
    "action_queue_builder": preload("res://src/battle_core/turn/action_queue_builder.gd"),
    "turn_loop_controller": preload("res://src/battle_core/turn/turn_loop_controller.gd"),
    "turn_resolution_service": preload("res://src/battle_core/turn/turn_resolution_service.gd"),
    "turn_selection_resolver": preload("res://src/battle_core/turn/turn_selection_resolver.gd"),
    "turn_field_lifecycle_service": preload("res://src/battle_core/turn/turn_field_lifecycle_service.gd"),
    "turn_limit_scoring_service": preload("res://src/battle_core/turn/turn_limit_scoring_service.gd"),
    "battle_result_service": preload("res://src/battle_core/turn/battle_result_service.gd"),
    "runtime_guard_service": preload("res://src/battle_core/turn/runtime_guard_service.gd"),
    "action_executor": preload("res://src/battle_core/actions/action_executor.gd"),
    "action_chain_context_builder": preload("res://src/battle_core/actions/action_chain_context_builder.gd"),
    "action_start_phase_service": preload("res://src/battle_core/actions/action_start_phase_service.gd"),
    "action_skill_effect_service": preload("res://src/battle_core/actions/action_skill_effect_service.gd"),
    "action_execution_resolution_service": preload("res://src/battle_core/actions/action_execution_resolution_service.gd"),
    "action_domain_guard": preload("res://src/battle_core/actions/action_domain_guard.gd"),
    "action_cast_service": preload("res://src/battle_core/actions/action_cast_service.gd"),
    "action_cast_direct_damage_pipeline": preload("res://src/battle_core/actions/action_cast_direct_damage_pipeline.gd"),
    "action_cast_skill_effect_dispatch_pipeline": preload("res://src/battle_core/actions/action_cast_skill_effect_dispatch_pipeline.gd"),
    "action_hit_resolution_service": preload("res://src/battle_core/actions/action_hit_resolution_service.gd"),
    "power_bonus_resolver": preload("res://src/battle_core/actions/power_bonus_resolver.gd"),
    "switch_action_service": preload("res://src/battle_core/actions/switch_action_service.gd"),
    "action_log_service": preload("res://src/battle_core/actions/action_log_service.gd"),
    "target_resolver": preload("res://src/battle_core/actions/target_resolver.gd"),
    "stat_calculator": preload("res://src/battle_core/math/stat_calculator.gd"),
    "mp_service": preload("res://src/battle_core/math/mp_service.gd"),
    "hit_service": preload("res://src/battle_core/math/hit_service.gd"),
    "damage_service": preload("res://src/battle_core/math/damage_service.gd"),
    "combat_type_service": preload("res://src/battle_core/math/combat_type_service.gd"),
    "leave_service": preload("res://src/battle_core/lifecycle/leave_service.gd"),
    "lifecycle_retention_policy": preload("res://src/battle_core/lifecycle/lifecycle_retention_policy.gd"),
    "faint_resolver": preload("res://src/battle_core/lifecycle/faint_resolver.gd"),
    "faint_killer_attribution_service": preload("res://src/battle_core/lifecycle/faint_killer_attribution_service.gd"),
    "faint_leave_replacement_service": preload("res://src/battle_core/lifecycle/faint_leave_replacement_service.gd"),
    "replacement_selector": preload("res://src/battle_core/lifecycle/default_replacement_selector.gd"),
    "replacement_service": preload("res://src/battle_core/lifecycle/replacement_service.gd"),
    "trigger_dispatcher": preload("res://src/battle_core/effects/trigger_dispatcher.gd"),
    "trigger_batch_runner": preload("res://src/battle_core/effects/trigger_batch_runner.gd"),
    "effect_queue_service": preload("res://src/battle_core/effects/effect_queue_service.gd"),
    "payload_executor": preload("res://src/battle_core/effects/payload_executor.gd"),
    "payload_unit_target_helper": preload("res://src/battle_core/effects/payload_handlers/payload_unit_target_helper.gd"),
    "payload_effect_event_helper": preload("res://src/battle_core/effects/payload_handlers/payload_effect_event_helper.gd"),
    "payload_numeric_handler": preload("res://src/battle_core/effects/payload_handlers/payload_numeric_handler.gd"),
    "payload_damage_runtime_service": preload("res://src/battle_core/effects/payload_handlers/payload_damage_runtime_service.gd"),
    "payload_resource_runtime_service": preload("res://src/battle_core/effects/payload_handlers/payload_resource_runtime_service.gd"),
    "payload_stat_mod_runtime_service": preload("res://src/battle_core/effects/payload_handlers/payload_stat_mod_runtime_service.gd"),
    "payload_state_handler": preload("res://src/battle_core/effects/payload_handlers/payload_state_handler.gd"),
    "payload_forced_replace_handler": preload("res://src/battle_core/effects/payload_handlers/payload_forced_replace_handler.gd"),
    "effect_instance_service": preload("res://src/battle_core/effects/effect_instance_service.gd"),
    "effect_instance_dispatcher": preload("res://src/battle_core/effects/effect_instance_dispatcher.gd"),
    "rule_mod_service": preload("res://src/battle_core/effects/rule_mod_service.gd"),
    "rule_mod_value_resolver": preload("res://src/battle_core/effects/rule_mod_value_resolver.gd"),
    "passive_skill_service": preload("res://src/battle_core/passives/passive_skill_service.gd"),
    "passive_item_service": preload("res://src/battle_core/passives/passive_item_service.gd"),
    "field_service": preload("res://src/battle_core/passives/field_service.gd"),
    "field_apply_service": preload("res://src/battle_core/passives/field_apply_service.gd"),
    "domain_clash_orchestrator": preload("res://src/battle_core/passives/domain_clash_orchestrator.gd"),
    "field_apply_context_resolver": preload("res://src/battle_core/passives/field_apply_context_resolver.gd"),
    "field_apply_conflict_service": preload("res://src/battle_core/passives/field_apply_conflict_service.gd"),
    "field_apply_log_service": preload("res://src/battle_core/passives/field_apply_log_service.gd"),
    "field_apply_effect_runner": preload("res://src/battle_core/passives/field_apply_effect_runner.gd"),
    "battle_logger": preload("res://src/battle_core/logging/battle_logger.gd"),
    "log_event_builder": preload("res://src/battle_core/logging/log_event_builder.gd"),
    "public_snapshot_builder": preload("res://src/battle_core/facades/public_snapshot_builder.gd"),
    "replay_runner": preload("res://src/battle_core/logging/replay_runner.gd"),
}

static func service_slots() -> PackedStringArray:
    var slots := PackedStringArray()
    for slot_name in SERVICE_SLOTS:
        slots.append(str(slot_name))
    return slots
