extends RefCounted
class_name BattleCoreComposer

const BattleCoreContainerScript := preload("res://src/composition/battle_core_container.gd")
const IdFactoryScript := preload("res://src/shared/id_factory.gd")
const RngServiceScript := preload("res://src/shared/rng_service.gd")
const LegalActionServiceScript := preload("res://src/battle_core/commands/legal_action_service.gd")
const CommandBuilderScript := preload("res://src/battle_core/commands/command_builder.gd")
const CommandValidatorScript := preload("res://src/battle_core/commands/command_validator.gd")
const BattleInitializerScript := preload("res://src/battle_core/turn/battle_initializer.gd")
const ActionQueueBuilderScript := preload("res://src/battle_core/turn/action_queue_builder.gd")
const TurnLoopControllerScript := preload("res://src/battle_core/turn/turn_loop_controller.gd")
const ActionExecutorScript := preload("res://src/battle_core/actions/action_executor.gd")
const TargetResolverScript := preload("res://src/battle_core/actions/target_resolver.gd")
const StatCalculatorScript := preload("res://src/battle_core/math/stat_calculator.gd")
const MpServiceScript := preload("res://src/battle_core/math/mp_service.gd")
const HitServiceScript := preload("res://src/battle_core/math/hit_service.gd")
const DamageServiceScript := preload("res://src/battle_core/math/damage_service.gd")
const LeaveServiceScript := preload("res://src/battle_core/lifecycle/leave_service.gd")
const FaintResolverScript := preload("res://src/battle_core/lifecycle/faint_resolver.gd")
const ReplacementServiceScript := preload("res://src/battle_core/lifecycle/replacement_service.gd")
const TriggerDispatcherScript := preload("res://src/battle_core/effects/trigger_dispatcher.gd")
const EffectQueueServiceScript := preload("res://src/battle_core/effects/effect_queue_service.gd")
const PayloadExecutorScript := preload("res://src/battle_core/effects/payload_executor.gd")
const EffectInstanceServiceScript := preload("res://src/battle_core/effects/effect_instance_service.gd")
const RuleModServiceScript := preload("res://src/battle_core/effects/rule_mod_service.gd")
const PassiveSkillServiceScript := preload("res://src/battle_core/passives/passive_skill_service.gd")
const PassiveItemServiceScript := preload("res://src/battle_core/passives/passive_item_service.gd")
const FieldServiceScript := preload("res://src/battle_core/passives/field_service.gd")
const BattleLoggerScript := preload("res://src/battle_core/logging/battle_logger.gd")
const LogEventBuilderScript := preload("res://src/battle_core/logging/log_event_builder.gd")
const ReplayRunnerScript := preload("res://src/battle_core/logging/replay_runner.gd")

func compose():
    var container = BattleCoreContainerScript.new()
    container.id_factory = IdFactoryScript.new()
    container.rng_service = RngServiceScript.new()
    container.legal_action_service = LegalActionServiceScript.new()
    container.command_builder = CommandBuilderScript.new()
    container.command_validator = CommandValidatorScript.new()
    container.battle_initializer = BattleInitializerScript.new()
    container.action_queue_builder = ActionQueueBuilderScript.new()
    container.turn_loop_controller = TurnLoopControllerScript.new()
    container.action_executor = ActionExecutorScript.new()
    container.target_resolver = TargetResolverScript.new()
    container.stat_calculator = StatCalculatorScript.new()
    container.mp_service = MpServiceScript.new()
    container.hit_service = HitServiceScript.new()
    container.damage_service = DamageServiceScript.new()
    container.leave_service = LeaveServiceScript.new()
    container.faint_resolver = FaintResolverScript.new()
    container.replacement_service = ReplacementServiceScript.new()
    container.trigger_dispatcher = TriggerDispatcherScript.new()
    container.effect_queue_service = EffectQueueServiceScript.new()
    container.payload_executor = PayloadExecutorScript.new()
    container.effect_instance_service = EffectInstanceServiceScript.new()
    container.rule_mod_service = RuleModServiceScript.new()
    container.passive_skill_service = PassiveSkillServiceScript.new()
    container.passive_item_service = PassiveItemServiceScript.new()
    container.field_service = FieldServiceScript.new()
    container.battle_logger = BattleLoggerScript.new()
    container.log_event_builder = LogEventBuilderScript.new()
    container.replay_runner = ReplayRunnerScript.new()
    return container
