from __future__ import annotations

from repo_consistency_common import GateContext
from repo_consistency_docs_gate_shared import FORMAL_VALIDATOR_BUCKETS


def run(ctx: GateContext) -> None:
    ctx.require_contains("docs/design/battle_content_schema.md", "Gojo / Sukuna / Kashimo / Obito", "schema four formal characters wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "candidate_skill_ids", "schema candidate skill pool contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "regular_skill_loadout_overrides", "schema setup override contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "max_stacks", "schema stack cap contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "once_per_battle", "schema once-per-battle skill contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "required_target_effects", "schema effect precondition contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "required_target_same_owner", "schema effect same-owner precondition contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "action_legality", "schema action legality contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "incoming_accuracy", "schema incoming accuracy contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "incoming_heal_final_mod", "schema incoming heal final mod contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "effect_stack_sum", "schema effect stack sum contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "power_bonus_self_effect_ids", "schema power bonus self effect ids contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "power_bonus_target_effect_ids", "schema power bonus target effect ids contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "power_bonus_per_stack", "schema power bonus per stack contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "config/formal_character_manifest.json", "schema formal character manifest wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "characters / matchups", "schema formal manifest bucket wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "formal_validators/shared/content_snapshot_formal_character_registry.gd", "schema runtime validator loader wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "当前 snapshot 实际出现的正式角色", "schema scoped formal validator wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "content_validator_script_path", "schema formal character validator path wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "pair_token", "schema pair token wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "baseline_script_path", "schema baseline script path wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "owned_pair_interaction_specs", "schema owned pair interaction wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "pair_initiator_bench_unit_ids", "schema pair initiator bench input wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "pair_responder_bench_unit_ids", "schema pair responder bench input wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "scenario_key", "schema pair interaction scenario key wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "owner_as_initiator_battle_seed / owner_as_responder_battle_seed", "schema pair interaction seed wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "shared_capability_ids", "schema shared capability ids wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "config/formal_character_capability_catalog.json", "schema capability catalog wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "required_fact_ids", "schema capability fact id wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "stop_and_specialize_when", "schema capability specialization boundary wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "顶层 `power = 0`", "schema damage-segment top-level power wording")
    ctx.require_contains("docs/design/battle_content_schema.md", "nullify_field_accuracy", "schema field accuracy nullify contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "incoming_action_final_mod", "schema incoming action final mod contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "required_incoming_command_types", "schema incoming action command filter contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "required_incoming_combat_type_ids", "schema incoming action combat type filter contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "action_actor", "schema action actor scope contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "`apply_field` payload requires `scope=field`", "schema apply_field scope contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "damage / heal / resource_mod / stat_mod / apply_effect / remove_effect", "schema unit-target payload scope contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "retention_mode", "schema stat retention contract")
    ctx.require_contains("docs/design/battle_content_schema.md", "persistent_stat_stages", "schema persistent stat stage contract")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "formal_setup_matchup_id", "formal character setup matchup checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "content_snapshot_paths_for_setup_result(battle_setup)", "formal character setup-scoped snapshot checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "content_validator_script_path", "formal character validator registry checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "pair_token", "formal character pair token checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "baseline_script_path", "formal character baseline path checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "pair_initiator_bench_unit_ids", "formal character pair initiator checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "pair_responder_bench_unit_ids", "formal character pair responder checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "owned_pair_interaction_specs", "formal character pair interaction spec checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "scenario_key", "formal character pair interaction scenario key checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "shared_capability_ids", "formal character shared capability checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "config/formal_character_capability_catalog.json", "formal character capability catalog checklist wording")
    ctx.require_contains("docs/design/formal_character_delivery_checklist.md", "unit_passive_contracts / skill_effect_contracts / ultimate_domain_contracts", "formal character tri-bucket checklist wording")
    ctx.require_contains("docs/design/formal_character_design_template.md", "shared_capability_ids", "formal character shared capability template wording")
    ctx.require_contains("docs/design/formal_character_design_template.md", "docs/design/formal_character_capability_catalog.md", "formal character capability catalog template wording")
    ctx.require_contains("docs/design/formal_character_design_template.md", "owned_pair_interaction_specs", "formal character pair interaction spec template wording")
    ctx.require_contains("docs/design/formal_character_design_template.md", "unit_passive_contracts / skill_effect_contracts / ultimate_domain_contracts", "formal character tri-bucket template wording")
    ctx.require_exists("docs/design/formal_character_capability_catalog.md", "formal character capability catalog design doc")
    ctx.require_contains("docs/design/formal_character_capability_catalog.md", "config/formal_character_capability_catalog.json", "formal character capability catalog config doc")
    ctx.require_contains("docs/design/formal_character_capability_catalog.md", "shared_capability_ids", "formal character capability manifest linkage doc")
    ctx.require_contains("docs/design/formal_character_capability_catalog.md", "required_fact_ids", "formal character capability fact id doc")
    ctx.require_contains("docs/design/formal_character_capability_catalog.md", "unit / skill / effect / field / passive / payload", "formal character capability collector dimensions doc")
    ctx.require_contains("docs/design/formal_character_capability_catalog.md", "stop_and_specialize_when", "formal character capability stop-and-specialize doc")
    ctx.require_contains("docs/design/kashimo_hajime_design.md", "kashimo_manager_smoke_suite.gd", "kashimo manager smoke delivery doc")
    ctx.require_contains("docs/design/kashimo_hajime_design.md", "tests/replay_cases/kashimo_cases.md", "kashimo fixed case delivery doc")
    ctx.require_contains("docs/design/kashimo_hajime_design.md", "kashimo_apply_water_leak_listeners", "kashimo water leak listener entry doc")
    ctx.require_contains("docs/design/kashimo_hajime_design.md", "kashimo_water_leak_self_listener", "kashimo water leak self listener doc")
    ctx.require_contains("docs/design/kashimo_hajime_design.md", "kashimo_water_leak_counter_listener", "kashimo water leak counter listener doc")
    ctx.require_contains("docs/design/sukuna_design.md", "max_stacks = 3", "sukuna kamado hard cap doc")
    ctx.require_contains("docs/design/sukuna_design.md", "不新增第 4 层", "sukuna kamado overflow ignore doc")
    ctx.require_contains("docs/design/sukuna_design.md", "max_mp", "sukuna matchup bst max_mp contract")
    ctx.require_contains("docs/rules/01_battle_format_and_visibility.md", "candidate_skill_ids", "rules candidate skill pool contract")
    ctx.require_contains("docs/rules/01_battle_format_and_visibility.md", "regular_skill_loadout_overrides", "rules setup override contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "required_target_effects", "rules effect precondition contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "required_target_same_owner", "rules effect same-owner precondition contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "max_stacks", "rules stack cap contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "on_receive_action_hit", "rules incoming action trigger contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "on_receive_action_damage_segment", "rules damage-segment trigger contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "retention_mode", "rules stat retention contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "persistent_stat_stages", "rules persistent stat stage contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "action_legality", "rules action legality contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "incoming_accuracy", "rules incoming accuracy contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "nullify_field_accuracy", "rules field accuracy nullify contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "incoming_action_final_mod", "rules incoming action final mod contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "incoming_heal_final_mod", "rules incoming heal final mod contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "required_incoming_command_types", "rules incoming action command filter contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "required_incoming_combat_type_ids", "rules incoming action combat type filter contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "action_actor", "rules action actor scope contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "`apply_field` payload requires `scope=field`", "rules apply_field scope contract")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "single` 只允许", "rules remove_effect single wording")
    ctx.require_contains("docs/rules/06_effect_schema_and_extension.md", "`all` 会按同一 `def_id` 一次清空", "rules remove_effect all wording")
    ctx.require_contains("docs/rules/03_stats_resources_and_damage.md", "incoming_accuracy", "rules incoming accuracy read-path")
    ctx.require_contains("docs/rules/03_stats_resources_and_damage.md", "max_mp", "rules sukuna matchup bst max_mp contract")
    ctx.require_contains("README.md", "content_validator_script_path", "README runtime validator registry doc")
    ctx.require_contains("README.md", "formal_setup_matchup_id", "README formal setup matchup doc")
    ctx.require_contains("README.md", "当前 content snapshot 实际已出现的正式角色", "README scoped formal validator doc")
    ctx.require_contains("README.md", "content_snapshot_paths_for_setup_result(battle_setup)", "README setup-scoped snapshot doc")
    ctx.require_contains("README.md", "pair_token", "README pair token wording")
    ctx.require_contains("README.md", "baseline_script_path", "README baseline path wording")
    ctx.require_contains("README.md", "owned_pair_interaction_specs", "README pair interaction spec wording")
    ctx.require_contains("README.md", "required_fact_ids", "README capability fact id wording")
    ctx.require_contains("README.md", "scenario_key", "README pair interaction scenario key wording")
    ctx.require_contains("README.md", "shared_capability_ids", "README shared capability doc")
    ctx.require_contains("README.md", "config/formal_character_capability_catalog.json", "README capability catalog doc")
    ctx.require_contains("README.md", "unit_passive_contracts / skill_effect_contracts / ultimate_domain_contracts", "README formal validator tri-bucket wording")
    ctx.require_contains("tests/README.md", "formal_setup_matchup_id", "tests README formal setup matchup doc")
    ctx.require_contains("tests/README.md", "只校验当前快照里实际出现的正式角色", "tests README scoped formal validator wording")
    ctx.require_contains("tests/README.md", "content_snapshot_paths_for_setup_result(battle_setup)", "tests README setup-scoped snapshot doc")
    ctx.require_contains("tests/README.md", "pair_token", "tests README pair token wording")
    ctx.require_contains("tests/README.md", "baseline_script_path", "tests README baseline path wording")
    ctx.require_contains("tests/README.md", "owned_pair_interaction_specs", "tests README pair interaction spec wording")
    ctx.require_contains("tests/README.md", "required_fact_ids", "tests README capability fact id wording")
    ctx.require_contains("tests/README.md", "scenario_key", "tests README pair interaction scenario key wording")
    ctx.require_contains("tests/README.md", "shared_capability_ids", "tests README shared capability doc")
    ctx.require_contains("tests/README.md", "config/formal_character_capability_catalog.json", "tests README capability catalog doc")
    ctx.require_contains("tests/README.md", "unit_passive_contracts / skill_effect_contracts / ultimate_domain_contracts", "tests README formal validator tri-bucket wording")

    for rel_path in [
        "README.md",
        "tests/README.md",
        "docs/design/formal_character_delivery_checklist.md",
        "docs/design/formal_character_design_template.md",
    ]:
        for bucket_name in FORMAL_VALIDATOR_BUCKETS:
            ctx.require_contains(rel_path, bucket_name, "complete formal validator bucket wording")
