from __future__ import annotations

from repo_consistency_common import GateContext
from repo_consistency_docs_gate_shared import CURRENT_REGRESSION_BASELINE_DOC, CURRENT_WORKFLOW_DOC


def run(ctx: GateContext) -> None:
    ctx.require_exists(CURRENT_WORKFLOW_DOC, "current development workflow design doc")
    ctx.require_exists(CURRENT_REGRESSION_BASELINE_DOC, "current stage regression baseline design doc")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "文档治理基线", "workflow documentation baseline section")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "哪些文档是规范源", "workflow source-of-truth wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "formal 产物同步入口", "workflow formal sync section")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "测试分类口径", "workflow test taxonomy section")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "Sandbox 日常试玩路径", "workflow sandbox section")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "测试入口与推荐跑法", "workflow test section")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "文档更新顺序与记录要求", "workflow documentation update section")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "BattleSandbox", "workflow sandbox main entry wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "bash tests/sync_formal_registry.sh", "workflow formal sync command wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "tests/run_with_gate.sh", "workflow unique total gate wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "gdUnit4 -> boot smoke -> suite reachability -> architecture constraints -> repo consistency -> sandbox smoke matrix", "workflow fixed total gate order wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "docs/design/current_stage_regression_baseline.md", "workflow regression baseline doc wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "gdUnit4 + test/", "workflow gdunit test tree wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "docs/records/tasks.md", "workflow tasks record wording")
    ctx.require_contains(CURRENT_WORKFLOW_DOC, "docs/records/decisions.md", "workflow decisions record wording")
    ctx.require_contains("README.md", "docs/design/current_development_workflow.md", "README workflow entry doc")
    ctx.require_contains("README.md", "docs/design/current_stage_regression_baseline.md", "README regression baseline doc")
    ctx.require_contains("README.md", "tests/check_sandbox_smoke_matrix.sh", "README sandbox smoke matrix doc")
    ctx.require_contains("README.md", "BattleSandbox", "README sandbox main entry wording")
    ctx.require_contains("README.md", "tests/run_with_gate.sh", "README unique total gate wording")
    ctx.require_contains("README.md", "tests/sync_formal_registry.sh", "README formal sync command doc")
    ctx.require_contains("tests/README.md", "docs/design/current_development_workflow.md", "tests README workflow entry doc")
    ctx.require_contains("tests/README.md", "docs/design/current_stage_regression_baseline.md", "tests README regression baseline doc")
    ctx.require_contains("tests/README.md", "tests/check_sandbox_smoke_matrix.sh", "tests README sandbox smoke matrix doc")
    ctx.require_contains("tests/README.md", "tests/sync_formal_registry.sh", "tests README formal sync command doc")
    ctx.require_contains("tests/README.md", "测试分类口径", "tests README test taxonomy wording")
    ctx.require_contains("tests/README.md", "tests/run_with_gate.sh", "tests README unique total gate wording")
    ctx.require_contains("tests/README.md", "BattleSandbox", "tests README sandbox wording")
    ctx.require_contains(CURRENT_REGRESSION_BASELINE_DOC, "tests/run_with_gate.sh", "regression baseline total gate command")
    ctx.require_contains(CURRENT_REGRESSION_BASELINE_DOC, "tests/check_sandbox_smoke_matrix.sh", "regression baseline smoke matrix command")
    ctx.require_contains(CURRENT_REGRESSION_BASELINE_DOC, "manual_battle_full_run.gd", "regression baseline headless helper command")
    ctx.require_contains(CURRENT_REGRESSION_BASELINE_DOC, "可启动", "regression baseline playability launch check")
    ctx.require_contains(CURRENT_REGRESSION_BASELINE_DOC, "能跑完一局", "regression baseline playability finish check")
    ctx.require_contains(CURRENT_REGRESSION_BASELINE_DOC, "统一终局摘要", "regression baseline summary wording")
    ctx.require_contains("docs/design/project_folder_structure.md", "test/suites", "project folder test suite tree wording")
    ctx.require_contains("docs/rules/README.md", "`docs/design/`", "rules README design reference wording")
