#!/usr/bin/env bash
set -euo pipefail

# Whitelist-keep cleanup for local test artifacts.
#
# Anything inside `reports/` and `tmp/` that is NOT explicitly listed below
# is removed. This inverts the previous "blacklist-delete" approach so that
# new noisy directories created by gdUnit/sandbox runs cannot silently pile
# up across runs.
#
# Whitelist entries are paths relative to the repo root.

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

KEEP_PATHS=(
  "reports/gdunit"
  "reports/manual_log"
  "tmp/preserved"
)

is_whitelisted() {
  local target="$1"
  local kept
  for kept in "${KEEP_PATHS[@]}"; do
    if [[ "$target" == "$kept" || "$target" == "$kept"/* ]]; then
      return 0
    fi
    # Keep parent dirs of whitelisted paths so the whitelisted child can survive.
    if [[ "$kept" == "$target"/* ]]; then
      return 0
    fi
  done
  return 1
}

prune_directory() {
  local dir="$1"
  if [[ ! -d "$dir" ]]; then
    return 0
  fi
  local entry rel
  while IFS= read -r -d '' entry; do
    rel="${entry#./}"
    if is_whitelisted "$rel"; then
      continue
    fi
    rm -rf "$entry"
  done < <(find "$dir" -mindepth 1 -maxdepth 1 -print0)
}

prune_directory "reports"
prune_directory "tmp"

# Drop top-level scratch dirs that have no preserved sub-path.
rm -rf .tmp

# Python / lint caches scattered across the tree.
find . -type d \( -name "__pycache__" -o -name ".ruff_cache" \) -prune -exec rm -rf {} +

# Best-effort: drop empty assets dir if it ended up generated by tooling.
rmdir assets 2>/dev/null || true

echo "LOCAL_ARTIFACT_CLEANUP_PASSED: kept whitelist (${KEEP_PATHS[*]}) and removed everything else under reports/ tmp/ plus Python caches"
