extends RefCounted

const WIRING_SPECS := [
	{"owner": "action_log_service", "dependency": "battle_logger", "source": "battle_logger"},
	{"owner": "action_log_service", "dependency": "log_event_builder", "source": "log_event_builder"},
	{"owner": "action_hit_resolution_service", "dependency": "hit_service", "source": "hit_service"},
	{"owner": "action_hit_resolution_service", "dependency": "rule_mod_service", "source": "rule_mod_service"},
	{"owner": "action_hit_resolution_service", "dependency": "rng_service", "source": "rng_service"},
	{"owner": "action_cast_service", "dependency": "mp_service", "source": "mp_service"},
	{"owner": "action_cast_service", "dependency": "action_hit_resolution_service", "source": "action_hit_resolution_service"},
	{"owner": "action_cast_service", "dependency": "target_resolver", "source": "target_resolver"},
	{"owner": "action_cast_service", "dependency": "trigger_batch_runner", "source": "trigger_batch_runner"},
	{"owner": "action_cast_service", "dependency": "action_log_service", "source": "action_log_service"},
	{"owner": "action_cast_service", "dependency": "action_cast_direct_damage_pipeline", "source": "action_cast_direct_damage_pipeline"},
	{"owner": "action_cast_service", "dependency": "action_cast_skill_effect_dispatch_pipeline", "source": "action_cast_skill_effect_dispatch_pipeline"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "power_bonus_resolver", "source": "power_bonus_resolver"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "damage_service", "source": "damage_service"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "combat_type_service", "source": "combat_type_service"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "stat_calculator", "source": "stat_calculator"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "rule_mod_service", "source": "rule_mod_service"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "faint_killer_attribution_service", "source": "faint_killer_attribution_service"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "action_log_service", "source": "action_log_service"},
	{"owner": "action_cast_direct_damage_pipeline", "dependency": "trigger_batch_runner", "source": "trigger_batch_runner"},
	{"owner": "action_cast_skill_effect_dispatch_pipeline", "dependency": "trigger_dispatcher", "source": "trigger_dispatcher"},
	{"owner": "action_cast_skill_effect_dispatch_pipeline", "dependency": "effect_queue_service", "source": "effect_queue_service"},
	{"owner": "action_cast_skill_effect_dispatch_pipeline", "dependency": "payload_executor", "source": "payload_executor"},
	{"owner": "action_cast_skill_effect_dispatch_pipeline", "dependency": "rng_service", "source": "rng_service"},
	{"owner": "action_cast_skill_effect_dispatch_pipeline", "dependency": "trigger_batch_runner", "source": "trigger_batch_runner"},
	{"owner": "switch_action_service", "dependency": "action_cast_service", "source": "action_cast_service"},
	{"owner": "switch_action_service", "dependency": "action_log_service", "source": "action_log_service"},
	{"owner": "switch_action_service", "dependency": "replacement_service", "source": "replacement_service"},
	{"owner": "action_executor", "dependency": "action_chain_context_builder", "source": "action_chain_context_builder"},
	{"owner": "action_executor", "dependency": "action_start_phase_service", "source": "action_start_phase_service"},
	{"owner": "action_executor", "dependency": "action_skill_effect_service", "source": "action_skill_effect_service"},
	{"owner": "action_executor", "dependency": "action_execution_resolution_service", "source": "action_execution_resolution_service"},
	{"owner": "action_executor", "dependency": "switch_action_service", "source": "switch_action_service"},
	{"owner": "action_executor", "dependency": "action_log_service", "source": "action_log_service"},
	{"owner": "action_executor", "dependency": "action_domain_guard", "source": "action_domain_guard"},
	{"owner": "action_start_phase_service", "dependency": "action_cast_service", "source": "action_cast_service"},
	{"owner": "action_start_phase_service", "dependency": "action_log_service", "source": "action_log_service"},
	{"owner": "action_skill_effect_service", "dependency": "action_cast_service", "source": "action_cast_service"},
	{"owner": "action_execution_resolution_service", "dependency": "action_cast_service", "source": "action_cast_service"},
	{"owner": "action_execution_resolution_service", "dependency": "action_log_service", "source": "action_log_service"},
	{"owner": "action_execution_resolution_service", "dependency": "action_skill_effect_service", "source": "action_skill_effect_service"},
	{"owner": "action_domain_guard", "dependency": "rule_mod_service", "source": "rule_mod_service"},
	{"owner": "action_domain_guard", "dependency": "domain_legality_service", "source": "domain_legality_service"},
]
