extends RefCounted
class_name EventTypes

const SYSTEM_BATTLE_INIT := "system:battle_init"
const SYSTEM_TURN_START := "system:turn_start"
const SYSTEM_TURN_END := "system:turn_end"
const SYSTEM_TURN_LIMIT := "system:turn_limit"
const SYSTEM_INVALID_BATTLE := "system:invalid_battle"
const ACTION_CAST := "action:cast"
const ACTION_CANCELLED_PRE_START := "action:cancelled_pre_start"
const ACTION_FAILED_POST_START := "action:failed_post_start"
const ACTION_HIT := "action:hit"
const ACTION_MISS := "action:miss"
const EFFECT_DAMAGE := "effect:damage"
const EFFECT_HEAL := "effect:heal"
const EFFECT_RESOURCE_MOD := "effect:resource_mod"
const EFFECT_STAT_MOD := "effect:stat_mod"
const EFFECT_APPLY_FIELD := "effect:apply_field"
const EFFECT_APPLY_EFFECT := "effect:apply_effect"
const EFFECT_REMOVE_EFFECT := "effect:remove_effect"
const EFFECT_FIELD_EXPIRE := "effect:field_expire"
const EFFECT_RULE_MOD_APPLY := "effect:rule_mod_apply"
const EFFECT_RULE_MOD_REMOVE := "effect:rule_mod_remove"
const STATE_ENTER := "state:enter"
const STATE_EXIT := "state:exit"
const STATE_SWITCH := "state:switch"
const STATE_FAINT := "state:faint"
const STATE_REPLACE := "state:replace"
const RESULT_BATTLE_END := "result:battle_end"
