extends RefCounted
class_name SandboxViewRefs

const PATH_STATUS_LABEL := "RootMargin/MainColumn/HeaderPanel/HeaderContent/StatusLabel"
const PATH_ERROR_LABEL := "RootMargin/MainColumn/HeaderPanel/HeaderContent/ErrorLabel"
const PATH_BATTLE_SUMMARY_LABEL := "RootMargin/MainColumn/HeaderPanel/HeaderContent/BattleSummaryLabel"
const PATH_SELECT_PANEL := "RootMargin/MainColumn/SelectPanel"
const PATH_CHARACTER_SCROLL := "RootMargin/MainColumn/SelectPanel/SelectContent/CharacterScroll"
const PATH_CHARACTER_CARDS := "RootMargin/MainColumn/SelectPanel/SelectContent/CharacterScroll/CharacterCards"
const PATH_BODY_SCROLL := "RootMargin/MainColumn/BodyRow"
const PATH_BODY_ROW := "RootMargin/MainColumn/BodyRow/BodyContent"
const PATH_ACTION_PANEL := "RootMargin/MainColumn/ActionPanel"
const PATH_RESULT_PANEL := "RootMargin/MainColumn/ResultPanel"
const PATH_RESULT_SUMMARY := "RootMargin/MainColumn/ResultPanel/ResultContent/ResultSummary"
const PATH_RESULT_RESTART_BUTTON := "RootMargin/MainColumn/ResultPanel/ResultContent/ResultButtons/ResultRestartButton"
const PATH_RETURN_SELECT_BUTTON := "RootMargin/MainColumn/ResultPanel/ResultContent/ResultButtons/ReturnSelectButton"
const PATH_P1_SUMMARY := "RootMargin/MainColumn/BodyRow/BodyContent/P1Panel/P1Content/P1Summary"
const PATH_EVENT_HEADER_LABEL := "RootMargin/MainColumn/BodyRow/BodyContent/EventPanel/EventContent/EventHeaderLabel"
const PATH_EVENT_LOG_TEXT := "RootMargin/MainColumn/BodyRow/BodyContent/EventPanel/EventContent/EventLogText"
const PATH_P2_SUMMARY := "RootMargin/MainColumn/BodyRow/BodyContent/P2Panel/P2Content/P2Summary"
const PATH_CONFIG_STATUS_LABEL := "RootMargin/MainColumn/ActionPanel/ActionContent/ConfigPanel/ConfigContent/ConfigStatusLabel"
const PATH_MATCHUP_SELECT := "RootMargin/MainColumn/ActionPanel/ActionContent/ConfigPanel/ConfigContent/ConfigGrid/MatchupSelect"
const PATH_BATTLE_SEED_INPUT := "RootMargin/MainColumn/ActionPanel/ActionContent/ConfigPanel/ConfigContent/ConfigGrid/BattleSeedInput"
const PATH_P1_MODE_SELECT := "RootMargin/MainColumn/ActionPanel/ActionContent/ConfigPanel/ConfigContent/ConfigGrid/P1ModeSelect"
const PATH_P2_MODE_SELECT := "RootMargin/MainColumn/ActionPanel/ActionContent/ConfigPanel/ConfigContent/ConfigGrid/P2ModeSelect"
const PATH_ACTION_HEADER_LABEL := "RootMargin/MainColumn/ActionPanel/ActionContent/ActionHeaderLabel"
const PATH_PENDING_LABEL := "RootMargin/MainColumn/ActionPanel/ActionContent/PendingLabel"
const PATH_PRIMARY_BUTTONS := "RootMargin/MainColumn/ActionPanel/ActionContent/PrimaryButtons"
const PATH_SWITCH_LABEL := "RootMargin/MainColumn/ActionPanel/ActionContent/SwitchLabel"
const PATH_SWITCH_BUTTONS := "RootMargin/MainColumn/ActionPanel/ActionContent/SwitchButtons"
const PATH_UTILITY_BUTTONS := "RootMargin/MainColumn/ActionPanel/ActionContent/UtilityButtons"
const PATH_RESTART_BUTTON := "RootMargin/MainColumn/ActionPanel/ActionContent/ControlButtons/RestartButton"
const PATH_REPLAY_CONTROLS := "RootMargin/MainColumn/ActionPanel/ActionContent/ControlButtons/ReplayControls"
const PATH_REPLAY_PREV_BUTTON := "RootMargin/MainColumn/ActionPanel/ActionContent/ControlButtons/ReplayControls/ReplayPrevButton"
const PATH_REPLAY_TURN_LABEL := "RootMargin/MainColumn/ActionPanel/ActionContent/ControlButtons/ReplayControls/ReplayTurnLabel"
const PATH_REPLAY_NEXT_BUTTON := "RootMargin/MainColumn/ActionPanel/ActionContent/ControlButtons/ReplayControls/ReplayNextButton"

var status_label: Label = null
var error_label: Label = null
var battle_summary_label: Label = null
var select_panel: PanelContainer = null
var character_scroll: ScrollContainer = null
var character_cards: GridContainer = null
var body_scroll: ScrollContainer = null
var body_row: HFlowContainer = null
var action_panel: PanelContainer = null
var result_panel: PanelContainer = null
var result_summary: RichTextLabel = null
var result_restart_button: Button = null
var return_select_button: Button = null
var p1_summary: RichTextLabel = null
var event_header_label: Label = null
var event_log_text: RichTextLabel = null
var p2_summary: RichTextLabel = null
var config_status_label: Label = null
var matchup_select: OptionButton = null
var battle_seed_input: LineEdit = null
var p1_mode_select: OptionButton = null
var p2_mode_select: OptionButton = null
var action_header_label: Label = null
var pending_label: Label = null
var primary_buttons: Container = null
var switch_label: Label = null
var switch_buttons: Container = null
var utility_buttons: Container = null
var restart_button: Button = null
var replay_controls: HBoxContainer = null
var replay_prev_button: Button = null
var replay_turn_label: Label = null
var replay_next_button: Button = null

func bind(root: Control) -> void:
	status_label = root.get_node(PATH_STATUS_LABEL) as Label
	error_label = root.get_node(PATH_ERROR_LABEL) as Label
	battle_summary_label = root.get_node(PATH_BATTLE_SUMMARY_LABEL) as Label
	select_panel = root.get_node(PATH_SELECT_PANEL) as PanelContainer
	character_scroll = root.get_node(PATH_CHARACTER_SCROLL) as ScrollContainer
	character_cards = root.get_node(PATH_CHARACTER_CARDS) as GridContainer
	body_scroll = root.get_node(PATH_BODY_SCROLL) as ScrollContainer
	body_row = root.get_node(PATH_BODY_ROW) as HFlowContainer
	action_panel = root.get_node(PATH_ACTION_PANEL) as PanelContainer
	result_panel = root.get_node(PATH_RESULT_PANEL) as PanelContainer
	result_summary = root.get_node(PATH_RESULT_SUMMARY) as RichTextLabel
	result_restart_button = root.get_node(PATH_RESULT_RESTART_BUTTON) as Button
	return_select_button = root.get_node(PATH_RETURN_SELECT_BUTTON) as Button
	p1_summary = root.get_node(PATH_P1_SUMMARY) as RichTextLabel
	event_header_label = root.get_node(PATH_EVENT_HEADER_LABEL) as Label
	event_log_text = root.get_node(PATH_EVENT_LOG_TEXT) as RichTextLabel
	p2_summary = root.get_node(PATH_P2_SUMMARY) as RichTextLabel
	config_status_label = root.get_node(PATH_CONFIG_STATUS_LABEL) as Label
	matchup_select = root.get_node(PATH_MATCHUP_SELECT) as OptionButton
	battle_seed_input = root.get_node(PATH_BATTLE_SEED_INPUT) as LineEdit
	p1_mode_select = root.get_node(PATH_P1_MODE_SELECT) as OptionButton
	p2_mode_select = root.get_node(PATH_P2_MODE_SELECT) as OptionButton
	action_header_label = root.get_node(PATH_ACTION_HEADER_LABEL) as Label
	pending_label = root.get_node(PATH_PENDING_LABEL) as Label
	primary_buttons = root.get_node(PATH_PRIMARY_BUTTONS) as Container
	switch_label = root.get_node(PATH_SWITCH_LABEL) as Label
	switch_buttons = root.get_node(PATH_SWITCH_BUTTONS) as Container
	utility_buttons = root.get_node(PATH_UTILITY_BUTTONS) as Container
	restart_button = root.get_node(PATH_RESTART_BUTTON) as Button
	replay_controls = root.get_node(PATH_REPLAY_CONTROLS) as HBoxContainer
	replay_prev_button = root.get_node(PATH_REPLAY_PREV_BUTTON) as Button
	replay_turn_label = root.get_node(PATH_REPLAY_TURN_LABEL) as Label
	replay_next_button = root.get_node(PATH_REPLAY_NEXT_BUTTON) as Button

func is_bound() -> bool:
	return status_label != null
